CREATE DATABASE centro_innovacion_un ;

USE centro_innovacion_un;

CREATE TABLE AUTOR (
  autorID VARCHAR(255) NOT NULL PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  afiliacion VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE TEMA (
  temaID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  autorID VARCHAR(255) NOT NULL,
  titulo VARCHAR(255) NOT NULL,
  link VARCHAR(255) ,
  FOREIGN KEY (autorID) REFERENCES AUTOR(autorID)
);

CREATE TABLE ARTICULO (
    articuloID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    autorID VARCHAR(255) NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    link VARCHAR(255) NOT NULL,
    cita_id VARCHAR(255),
    autores VARCHAR(255),
    publicacion VARCHAR(255),
    año INT ,
    FOREIGN KEY (autorID) REFERENCES AUTOR(autorID)
);

CREATE TABLE AUTOR_TEMA (
  autorID VARCHAR(255) NOT NULL,
  temaID INT NOT NULL,
  PRIMARY KEY (autorID, temaID),
  FOREIGN KEY (autorID) REFERENCES AUTOR(autorID),
  FOREIGN KEY (temaID) REFERENCES TEMA(temaID)
);



